apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: gateway-service
data:
  # Non-sensitive configuration key-value pairs
  XYZ_API_URL: "http://api.xyzservice.com/v1:8080"
